spring:
  application:    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashishb888/spring-cloud-config-2.2-poc/config-repo
          
server:
  port: 9000
  
logging:  file:    name: /var/tmp/logs/spring-cloud-config-server/spring-cloud-config-server
  level:    root: INFO
    poc.springcloud: DEBUG